[package]
name = "hebb"
version = "0.0.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "hebb"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[features]
default = []
#gpu = []

#[build-dependencies]
#lalrpop = "^0.16"

#[dev-dependencies]

[dependencies]
#lalrpop-util = "^0.16"
#lazy_static = "*"
#num-traits = "^0.2"
#parking_lot = { version = "^0.5", features = ["nightly"] }
#rand = "^0.5"
regex = "*"
#plex = "*"
plex = { path = "../plex", default-features = false, features = ["lexer"] }
