[package]
name = "hebb"
version = "0.0.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
edition = "2018"

[lib]
name = "hebb"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[features]
default = []
gpu = []

#[dev-dependencies]

[dependencies]
#lazy_static = "*"
#num-traits = "^0.2"
#parking_lot = { version = "*", features = ["nightly"] }
rand = "^0.6"
rdrand = { path = "../rdrand" }
regex = "*"
#pbrtree = { path = "../pbrtree" }
#plex = "*"
plex = { path = "../plex", default-features = false, features = ["lexer"] }
